/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IADentalClinic;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author aryanghosh
 */
public class FindPatient extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null;
    PreparedStatement pst2=null;
    ResultSet rs=null;
    ResultSet rs1=null; 
    ResultSet rs2=null;

    /**
     * Creates new form FindPatient
     */
    public FindPatient() {
        initComponents();
        conn=MySQLConnect.ConnectDB();
         
        String sql="select id from patients";
        try{
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String name=rs.getString("id");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        displayItem();
    
    
    String sql2="select name from patients";
        try{
            pst1 = conn.prepareStatement(sql2);
            ResultSet rs1 = pst1.executeQuery();
            while(rs1.next()){
                String name1=rs1.getString("name");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        displayItem();
    }
    
    
    public void displayItem() 
    {//performs displayitem
        String sql1 ="select * from patients";
        try {//Selects data from ‘patients’ database.
            pst1 = conn.prepareStatement(sql1);
             rs=pst1.executeQuery();
             tPatient.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException ex) {
            Logger.getLogger(NewStaff.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }  
    public void displayAllItem(String id)
    {//performs displayallitem
        try{        
            String sql2 ="select * from patients where id=?";//Selects data with respect to id 
                pst1=conn.prepareStatement(sql2);
                pst1.setString(1, id);
                rs1=pst1.executeQuery();
                tPatient.setModel(DbUtils.resultSetToTableModel(rs1));
            } catch (SQLException ex) {
                Logger.getLogger(NewStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
           }
    public void displayAllItemName(String name)
    {//performs displayallitemname
        try{        
            String sql3 ="select * from patients where name=?";//Selects data with respect to name 
                pst2=conn.prepareStatement(sql3);
                pst2.setString(1, name);
                rs2=pst2.executeQuery();
                tPatient.setModel(DbUtils.resultSetToTableModel(rs2));
            } catch (SQLException ex) {
                Logger.getLogger(NewStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
           }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bIDSearch = new javax.swing.JButton();
        tfIDSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPatient = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        bMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfSex = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfMob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfMed = new javax.swing.JTextField();
        tfTeeth = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bDelete = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNameSearch = new javax.swing.JTextField();
        bNameSearch = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        bPrint = new javax.swing.JButton();
        tfIDSearch1 = new javax.swing.JTextField();
        bIDSearch1 = new javax.swing.JButton();

        bIDSearch.setText("Search");
        bIDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIDSearchActionPerformed(evt);
            }
        });

        tfIDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDSearchActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel1.setText("Patient Search ");

        tPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tPatient);

        jLabel2.setText("ID:");

        tfID.setText(" ");

        bMenu.setText("Menu");
        bMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuActionPerformed(evt);
            }
        });

        jLabel3.setText("Full Name");

        tfName.setText(" ");

        jLabel4.setText("Age");

        tfAge.setText(" ");

        jLabel5.setText("Sex");

        tfSex.setText(" ");

        tfAddress.setText(" ");

        jLabel6.setText("Address ");

        tfMob.setText(" ");

        jLabel7.setText("Mobile No");

        jLabel8.setText("Email ID");

        tfEmail.setText(" ");

        jLabel9.setText("Medical History");

        tfMed.setText(" ");

        tfTeeth.setText(" ");

        jLabel10.setText("Teeth appearance");

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bSave.setText("Save Changes");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        jLabel12.setText("Name:");

        bNameSearch.setText("Search Name");
        bNameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNameSearchActionPerformed(evt);
            }
        });

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });

        tfIDSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDSearch1ActionPerformed(evt);
            }
        });

        bIDSearch1.setText("Search ID");
        bIDSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIDSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSave))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMob, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel8)
                                .addGap(153, 153, 153))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tfMed, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfTeeth)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfIDSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(bIDSearch1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(bNameSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfSex, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bMenu)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1)
                    .addComponent(tfNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIDSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameSearch)
                    .addComponent(bRefresh)
                    .addComponent(bIDSearch1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPrint)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTeeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDelete)
                    .addComponent(bSave)))
        );

        setSize(new java.awt.Dimension(882, 623));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        String Sql="delete from patients where id=?";
        try{// the data is obtained and then deleted from the database
            pst=conn.prepareStatement(Sql);
            pst.setInt(1,Integer.parseInt(this.tfID.getText()));
            int i = pst.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Patient Successfully Deleted");
                this.dispose();
                new FindPatient().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Patient Data not Deleted!");
            }
            //The ‘try-catch’ phrases examine errors while connecting to database.
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        String Sql="update patients set name=?, age=?, sex=?, address=?, mobno=?, email=?, medicalhistory=?, teethappearance=? where id=?";
        try{// the data is stored in temporary variables and then updates the database

            pst=conn.prepareStatement(Sql);

            pst.setString(1,this.tfName.getText());
            pst.setString(2,this.tfAge.getText());
            pst.setString(3,this.tfSex.getText());
            pst.setString(4,this.tfAddress.getText());
            pst.setString(5,this.tfMob.getText());
            pst.setString(6,this.tfEmail.getText());
            pst.setString(7,this.tfMed.getText());
            pst.setString(8,this.tfTeeth.getText());
            pst.setString(9,this.tfID.getText());
            // every field in the particular database will be updated with new data
            int i = pst.executeUpdate();
            if(i>0){
            //if all conditions are matched the new data will be stored
                JOptionPane.showMessageDialog(null, "Patient Data Updated!");
                this.dispose();
                new FindPatient().setVisible(true);
            }
            else{// an error message will be displayed if there is an issue wiht the new data 
                JOptionPane.showMessageDialog(null,"Error! Data not Saved");
            }
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void tPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPatientMouseClicked
        DefaultTableModel model = (DefaultTableModel)tPatient.getModel();
        int i = tPatient.getSelectedRow();//retrieving data
        this.tfID.setText(model.getValueAt(i, 0).toString());
        this.tfName.setText(model.getValueAt(i, 1).toString());
        this.tfAge.setText(model.getValueAt(i, 2).toString());
        this.tfSex.setText(model.getValueAt(i, 3).toString());
        this.tfAddress.setText(model.getValueAt(i, 4).toString());
        this.tfMob.setText(model.getValueAt(i, 5).toString());
        this.tfEmail.setText(model.getValueAt(i, 6).toString());
        this.tfMed.setText(model.getValueAt(i, 7).toString());
        this.tfTeeth.setText(model.getValueAt(i, 8).toString());// all data will be displayed in text boxes
    }//GEN-LAST:event_tPatientMouseClicked

    private void bMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuActionPerformed
        if (login.glv==1)
                {
                    this.dispose();
                    new AdminDashboard().setVisible(true);
                }
                else
                {
                    this.dispose();
                    new EmployeeDashboard().setVisible(true);
                }
    }//GEN-LAST:event_bMenuActionPerformed

    private void bNameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNameSearchActionPerformed
        String sql ="select * from patients where name=?";
    try{// retrieval of data from the database
        pst = conn.prepareStatement(sql);// connectivity to database
        pst.setString(1,this.tfNameSearch.getText());// reading of data
        rs=pst.executeQuery();
      this.tPatient.setModel(DbUtils.resultSetToTableModel(rs));
           
           
        } catch (SQLException ex) {
            Logger.getLogger(FindStaff.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_bNameSearchActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        this.dispose();
        new FindPatient().setVisible(true);
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        MessageFormat header = new MessageFormat("Data Summary");
        MessageFormat footer = new MessageFormat(".");
        try{

            tPatient.print(JTable.PrintMode.NORMAL, header, footer);

        }
        catch (java.awt.print.PrinterException e){
            System.err.format("Cannot Print Bill", e.getMessage());

        }
    }//GEN-LAST:event_bPrintActionPerformed

    private void bIDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIDSearchActionPerformed
        String sql ="select * from newstaff where id=?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,this.tfIDSearch.getText());
            rs=pst.executeQuery();
            this.tPatient.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(FindStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bIDSearchActionPerformed

    private void tfIDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDSearchActionPerformed

    private void tfIDSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDSearch1ActionPerformed

    private void bIDSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIDSearch1ActionPerformed
        String sql ="select * from newstaff where id=?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,this.tfIDSearch.getText());
            rs=pst.executeQuery();
            this.tPatient.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(FindStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bIDSearch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bIDSearch;
    private javax.swing.JButton bIDSearch1;
    private javax.swing.JButton bMenu;
    private javax.swing.JButton bNameSearch;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tPatient;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfIDSearch;
    private javax.swing.JTextField tfIDSearch1;
    private javax.swing.JTextField tfMed;
    private javax.swing.JTextField tfMob;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNameSearch;
    private javax.swing.JTextField tfSex;
    private javax.swing.JTextField tfTeeth;
    // End of variables declaration//GEN-END:variables
}
