/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IADentalClinic;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author aryanghosh
 */
public class StaffSearch extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null;
    PreparedStatement pst2=null;
    ResultSet rs=null;
    ResultSet rs1=null;
    ResultSet rs2=null;

    /**
     * Creates new form StaffSearch
     */
    public StaffSearch() {
        initComponents();
        conn=MySQLConnect.ConnectDB();
        cboID.removeAllItems(); 
        cboName.removeAllItems();  
        String sql="select id from newstaff";
        try{
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String name=rs.getString("id");
                cboID.addItem(name);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        displayItem();
    
    
    String sql2="select name from newstaff";
        try{
            pst1 = conn.prepareStatement(sql2);
            ResultSet rs1 = pst1.executeQuery();
            while(rs1.next()){
                String name1=rs1.getString("name");
                cboName.addItem(name1);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        displayItem();
    }
    
    
    public void displayItem() 
    {
        String sql1 ="select * from newstaff";
        try {
            pst1 = conn.prepareStatement(sql1);
             rs=pst1.executeQuery();
             tStaff.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException ex) {
            Logger.getLogger(NewStaff.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }  
    public void displayAllItem(String id)
    {
        try{        
            String sql2 ="select * from newstaff where id=?";
                pst1=conn.prepareStatement(sql2);
                pst1.setString(1, id);
                rs1=pst1.executeQuery();
                tStaff.setModel(DbUtils.resultSetToTableModel(rs1));
            } catch (SQLException ex) {
                Logger.getLogger(NewStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
           }
    public void displayAllItemName(String name)
    {
        try{        
            String sql3 ="select * from newstaff where name=?";
                pst2=conn.prepareStatement(sql3);
                pst2.setString(1, name);
                rs2=pst2.executeQuery();
                tStaff.setModel(DbUtils.resultSetToTableModel(rs2));
            } catch (SQLException ex) {
                Logger.getLogger(NewStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tStaff = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboID = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboName = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tStaff);

        jLabel1.setText("ID");

        cboID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboIDItemStateChanged(evt);
            }
        });
        cboID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        cboName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNameItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboIDActionPerformed

    private void cboIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboIDItemStateChanged
        displayAllItem((String) this.cboID.getSelectedItem()); 
    }//GEN-LAST:event_cboIDItemStateChanged

    private void tStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tStaffMouseClicked

    }//GEN-LAST:event_tStaffMouseClicked

    private void cboNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNameItemStateChanged
        displayAllItemName((String) this.cboName.getSelectedItem());
    }//GEN-LAST:event_cboNameItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboID;
    private javax.swing.JComboBox<String> cboName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tStaff;
    // End of variables declaration//GEN-END:variables
}
